version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      NEON_HOST: ep-patient-boat-a1wxvox2-pooler.ap-southeast-1.aws.neon.tech
      NEON_PORT: 5432
      NEON_DB: neondb
      NEON_USER: neondb_owner
      NEON_PASSWORD: npg_w1POTCuisX6v
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/homelink_db
      SPRING_DATASOURCE_USERNAME: homelink_user
      SPRING_DATASOURCE_PASSWORD: securepassword123

volumes:
  db-data:
