services:
  app:
    build: .
    container_name: api-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      # This explicitly maps the system env var to the container env var
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    restart: always
